<?
    /**
     * STEPS TO FOLLOW ON THIS FILE:
     * 1. fill all of the required data below
     * 2. change $fb['on'] to true
     * 3. rename this file to _fb_.inc
     * 4. ?????????????
     * 5. PROFIT!
     */

    $fb = Array();
    $fb['on'] = false;

    if($fb['on']) {
        $fb['app_id'] = "";     // aplication's ID
        $fb['app_secret'] = ""; // application's secret
        $fb['scope'] = "";      // permissions required by application

        $fb['sdk'] = "";        // location of facebook.php
        $fb['xmlns'] = "";      // sometimes it's required to add this to <html> node
    }
?>
 
